[project]
name = "bmad-ai-project-context-vu-venv-todo-no-sub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "josheeg", email = "josheeg@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
bmad-ai-project-context-vu-venv-todo-no-sub = "bmad_ai_project_context_vu_venv_todo_no_sub:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
